### ISSUE TITLE
On CentOS 7 this doesn't works.

### ISSUE THREAD

**Issue by forlayo** [prahladyeri/hotspotd#16]
```
[root@localhost hotspotd-0.1.4]# sudo hotspotd start
Verifying connections
Wireless interface could not be found on your device.
Traceback (most recent call last):
  File "/bin/hotspotd", line 22, in <module>
    hotspotd.main.main(args)
  File "/usr/lib/python2.7/site-packages/hotspotd/main.py", line 302, in main
    dc =json.load(open('hotspotd.json'))
IOError: [Errno 2] No such file or directory: 'hotspotd.json'
```

```
[root@localhost hotspotd-0.1.4]# ifconfig
enp1s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.16.1.27  netmask 255.255.255.0  broadcast 172.16.1.255
        inet6 fe80::2e0:4cff:fe68:33c3  prefixlen 64  scopeid 0x20<link>
        ether 00:e0:4c:68:33:c3  txqueuelen 1000  (Ethernet)
        RX packets 12704  bytes 9533345 (9.0 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 7091  bytes 1226289 (1.1 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 0  (Local Loopback)
        RX packets 6  bytes 560 (560.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 6  bytes 560 (560.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlp2s0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 00:1e:2a:7d:82:af  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by prahladyeri** [comment]
Perhaps the different naming convention in centos (wlp2s0) confuses the app.

I think the wlano convention may have been hard-coded somewhere. Will check the code and revert back.

**Comment by stanzani** [comment]
I had the same problem.
CentOs 7 doesn't have the command iwconfig.
So... you need to install it:
yum install epel-release
and 
yum install wireless-tools

**Comment by prahladyeri** [comment]
@forlayo  Are you still using this daemon?
