### ISSUE TITLE
hotspotd start is not working in fedora

### ISSUE THREAD

**Issue by gaurav36** [prahladyeri/hotspotd#27]
hi,

whenever i am starting hotspotd in fedora its saying that you need root permission. i am already a root user.

[root@dhcp-0-40 hotspotd-0.1.4]# ls
build  cli.py  hotspotd  **init**.py  main.py  PKG-INFO  run.dat  setup.py
[root@dhcp-0-40 hotspotd-0.1.4]# hotspotd start
You need root permissions to do this, sloth!
[root@dhcp-0-40 hotspotd-0.1.4]# strace hostspotd start
strace: Can't stat 'hostspotd': No such file or directory
[root@dhcp-0-40 hotspotd-0.1.4]# /bin/host
host         hostid       hostname     hostnamectl  
[root@dhcp-0-40 hotspotd-0.1.4]# type hostpotd
bash: type: hostpotd: not found
[root@dhcp-0-40 hotspotd-0.1.4]# type hotspotd
hotspotd is hashed (/bin/hotspotd)
[root@dhcp-0-40 hotspotd-0.1.4]# /bin/hotspotd start
You need root permissions to do this, sloth!
[root@dhcp-0-40 hotspotd-0.1.4]# sudo /bin/hotspotd start
You need root permissions to do this, sloth!
[root@dhcp-0-40 hotspotd-0.1.4]# sudo hotspotd start
You need root permissions to do this, sloth!
[root@dhcp-0-40 hotspotd-0.1.4]# 

i have tested it with latest hotspotd repo but the same error is coming.

any clue regarding this issue?

**Comment by prahladyeri** [comment]
Which version of Hotspotd are you using? And what version is Fedora?

**Comment by gaurav36** [comment]
Hi @prahladyeri  previously i have tried latest version then i thought it might not be stable then i tried 0.1.4 version. and error remain the same. I am using fedora 23.

root problem have solved by commenting code in /usr/bin/hotspotd. now i need to do some configuration. will update you if i face any issue.

Thanks :)

**Comment by prahladyeri** [comment]
@gaurav36 I believe you've solved your problem by commenting this block of code in `/usr/bin/hotspotd`:

	#check root or not
	if os.getenv('USER') != 'root':
		print "You need root permissions to do this, sloth!"
		sys.exit(1)

If yes, there is a good chance that os.getenv() python function is not working on your fedora version. When you get time just run `python` and following two commands in the interpreter:

    import os
    os.getenv('USER')

And paste me the output of that. This will help me make a permanent fix in code.

**Comment by gaurav36** [comment]
here is the output: 
[root@dhcp-0-40 hotspotd-0.1.5]# python
Python 2.7.10 (default, Sep  8 2015, 17:20:17) 
[GCC 5.1.1 20150618 (Red Hat 5.1.1-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.getenv('USER')
'garg'
>>> 

I think its not going to work here. better to do following check

>>> os.getenv("HOME")
'/root'
>>> os.getenv('HOME')
'/root'
>>> 

you can perform various check by getting os environment also. let me know if you need a patch or any other help for finding this out.

P.S. still need to do configuration. first attempt of configuration was unsuccessful

**Comment by prahladyeri** [comment]
Thanks. os.getenv('HOME') is a good approach but not fool proof. For example, if I use sudo to start the daemon, the variable will be `/home/prahlad` instead of `/root`. I'm working on another better approach.

BTW, what exact configuration are you not able to setup? Did you try `hotspotd configure` command?

**Comment by shubhz14** [comment]
It is working perfectly fine as a root user with the command 'sudo hotspotd start' on my Redhat Enterprise Linux 7.
Although It doesn't makes any sense using 'sudo' command as a root user!

**Comment by shubhz14** [comment]
It is working perfectly fine as a root user with the command 'sudo hotspotd start' on my Redhat Enterprise Linux 7.
Although It doesn't makes any sense using 'sudo' command as a root user!

![screenshot from 2016-06-21 11 23 27](https://cloud.githubusercontent.com/assets/9039150/16219269/c3aeebd0-37a2-11e6-88fb-23c231c76527.png)

**Comment by prahladyeri** [comment]
I believe that sloth message you are getting because the root check wasn't being done in the earlier versions. Did you try out the latest version of hotspotd?

**Comment by prahladyeri** [comment]
Closing as there has been no activity.

**Comment by Ljay764** [comment]
hi 
i am facing this error.
Verifying connections
Wireless interface could not be found on your device.
Traceback (most recent call last):
  File "/usr/local/bin/hotspotd", line 22, in <module>
    hotspotd.main.main(args)
  File "/usr/local/lib/python2.7/dist-packages/hotspotd/main.py", line 310, in main
    dc =json.load(open('hotspotd.json'))
IOError: [Errno 2] No such file or directory: 'hotspotd.json'
